### ISSUE TITLE
golang 1.10

### ISSUE THREAD

**Issue by ghost** [vladimirvivien/gosh#2]
I know gosh is not yet supporting Mac but go version 1.10 now able to compile plugins for MacOS; however after trying to execute gosh I got the next output:

```
gosh> sys
runtime: bad pointer in frame main.main.func1 at 0xc420063f88: 0x4
fatal error: invalid pointer found on stack

runtime stack:
runtime.throw(0x50f0288, 0x1e)
	/usr/local/Cellar/go/1.10/libexec/src/runtime/panic.go:619 +0x81 fp=0x7ffeefbfeba0 sp=0x7ffeefbfeb80 pc=0x5028c61
runtime.adjustpointers(0xc420063ea8, 0x7ffeefbfec98, 0x7ffeefbff068, 0x41b7c18, 0x41c0840)
	/usr/local/Cellar/go/1.10/libexec/src/runtime/stack.go:592 +0x23e fp=0x7ffeefbfec10 sp=0x7ffeefbfeba0 pc=0x503c6be
runtime.adjustframe(0x7ffeefbfef78, 0x7ffeefbff068, 0x41c0840)
	/usr/local/Cellar/go/1.10/libexec/src/runtime/stack.go:663 +0x32c fp=0x7ffeefbfecc8 sp=0x7ffeefbfec10 pc=0x503ca0c
runtime.gentraceback(0xffffffffffffffff, 0xffffffffffffffff, 0x0, 0xc420078780, 0x0, 0x0, 0x7fffffff, 0x50f34c8, 0x7ffeefbff068, 0x0, ...)
	/usr/local/Cellar/go/1.10/libexec/src/runtime/traceback.go:355 +0x136c fp=0x7ffeefbfefe0 sp=0x7ffeefbfecc8 pc=0x504576c
runtime.copystack(0xc420078780, 0x2000, 0x7ffeefbff101)
	/usr/local/Cellar/go/1.10/libexec/src/runtime/stack.go:891 +0x26e fp=0x7ffeefbff198 sp=0x7ffeefbfefe0 pc=0x503d4fe
runtime.newstack()
	/usr/local/Cellar/go/1.10/libexec/src/runtime/stack.go:1063 +0x310 fp=0x7ffeefbff328 sp=0x7ffeefbff198 pc=0x503d910
runtime: unexpected return pc for runtime.morestack called from 0x0
stack: frame={sp:0x7ffeefbff328, fp:0x7ffeefbff330} stack=[0x7ffeefb7fed0,0x7ffeefbff350)
00007ffeefbff228:  00000000041d1460  00007ffeefbff278
00007ffeefbff238:  00000000040157ac <runtime.(*mcentral).grow+236>  000000c41fff79ff
00007ffeefbff248:  000000c400000000  000000000426ba28
00007ffeefbff258:  000000000426ba28  000000000402869a <runtime.mach_semrelease+26>
00007ffeefbff268:  000000c420078780  000000c420052cf8
00007ffeefbff278:  00000000050af2dc <plugin/unnamed-0069ea828d7ffa11ef4c6308dd62ff6f39b2904d.(*sysinfoCmd).Exec+140>  000000c420078780
00007ffeefbff288:  0000000000000000  0000000000000000
00007ffeefbff298:  0000000000000000  0000000000000000
00007ffeefbff2a8:  00007ffeefbff2c0  0000000004035feb <runtime.acquirep+43>
00007ffeefbff2b8:  000000c420026500  00007ffeefbff2e0
00007ffeefbff2c8:  0000000004033fdf <runtime.exitsyscallfast_pidle+143>  000000c420026500
00007ffeefbff2d8:  000000c420026500  00007ffeefbff310
00007ffeefbff2e8:  0000000004052511 <runtime.exitsyscallfast.func1+65>  0000000000000001
00007ffeefbff2f8:  000000c420026500  000000c420078780
00007ffeefbff308:  000000c420052a7f  000000c420052aa0
00007ffeefbff318:  000000c420052d50  000000000504b739 <runtime.morestack+137>
00007ffeefbff328: <0000000000000000 >00007ffeefbff380
00007ffeefbff338:  0000000004052e03 <runtime.rt0_go+515>  00007ffeefbff380
00007ffeefbff348:  0000000004052e0a <runtime.rt0_go+522>
runtime.morestack()
	/usr/local/Cellar/go/1.10/libexec/src/runtime/asm_amd64.s:480 +0x89 fp=0x7ffeefbff330 sp=0x7ffeefbff328 pc=0x504b739

goroutine 19 [copystack]:
plugin/unnamed-0069ea828d7ffa11ef4c6308dd62ff6f39b2904d.sysinfoCmd.Exec(0x50ec1aa, 0x3, 0x4140460, 0xc420098660, 0xc4200c0640, 0x1, 0xa, 0x40de290, 0xc4200cc900, 0xc4200cc938, ...)
	/Users/carlos.morales/Code/gosh/plugins/syscmd.go:119 +0x63c fp=0xc420063cf8 sp=0xc420063cf0 pc=0x50ae6ac
plugin/unnamed-0069ea828d7ffa11ef4c6308dd62ff6f39b2904d.(*sysinfoCmd).Exec(0x50fff20, 0x4140460, 0xc420098660, 0xc4200c0640, 0x1, 0xa, 0xa, 0x0, 0x4, 0x180)
	<autogenerated>:1 +0x8c fp=0xc420063d60 sp=0xc420063cf8 pc=0x50af2dc
main.(*Goshell).handle(0xc420098360, 0x4140460, 0xc420098660, 0xc4200a8160, 0x4, 0x0, 0x0, 0x0, 0x0)
	/Users/carlos.morales/Code/gosh/shell/gosh.go:111 +0x297 fp=0xc420063e58 sp=0xc420063d60 pc=0x40dfe67
main.main.func1(0x4140460, 0xc420098660, 0xc420098360)
	/Users/carlos.morales/Code/gosh/shell/gosh.go:179 +0x270 fp=0xc420063fc8 sp=0xc420063e58 pc=0x40e0a80
runtime.goexit()
	/usr/local/Cellar/go/1.10/libexec/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc420063fd0 sp=0xc420063fc8 pc=0x40558b1
created by main.main
	/Users/carlos.morales/Code/gosh/shell/gosh.go:166 +0x4d5

goroutine 1 [select (no cases)]:
runtime.gopark(0x0, 0x0, 0x4129708, 0x11, 0x10, 0x1)
	/usr/local/Cellar/go/1.10/libexec/src/runtime/proc.go:291 +0x11a fp=0xc420067e68 sp=0xc420067e48 pc=0x402cd4a
runtime.block()
	/usr/local/Cellar/go/1.10/libexec/src/runtime/select.go:192 +0x4c fp=0xc420067ea8 sp=0xc420067e68 pc=0x403addc
main.main()
	/Users/carlos.morales/Code/gosh/shell/gosh.go:189 +0x4da fp=0xc420067f88 sp=0xc420067ea8 pc=0x40e07fa
runtime.main()
	/usr/local/Cellar/go/1.10/libexec/src/runtime/proc.go:198 +0x212 fp=0xc420067fe0 sp=0xc420067f88 pc=0x402c8f2
runtime.goexit()
	/usr/local/Cellar/go/1.10/libexec/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc420067fe8 sp=0xc420067fe0 pc=0x40558b1

goroutine 2 [force gc (idle)]:
runtime.gopark(0x412fe90, 0x41d0fa0, 0x4128ff7, 0xf, 0x412fd14, 0x1)
	/usr/local/Cellar/go/1.10/libexec/src/runtime/proc.go:291 +0x11a fp=0xc420044768 sp=0xc420044748 pc=0x402cd4a
runtime.goparkunlock(0x41d0fa0, 0x4128ff7, 0xf, 0x14, 0x1)
	/usr/local/Cellar/go/1.10/libexec/src/runtime/proc.go:297 +0x5e fp=0xc4200447a8 sp=0xc420044768 pc=0x402cdfe
runtime.forcegchelper()
	/usr/local/Cellar/go/1.10/libexec/src/runtime/proc.go:248 +0xcc fp=0xc4200447e0 sp=0xc4200447a8 pc=0x402cb8c
runtime.goexit()
	/usr/local/Cellar/go/1.10/libexec/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc4200447e8 sp=0xc4200447e0 pc=0x40558b1
created by runtime.init.4
	/usr/local/Cellar/go/1.10/libexec/src/runtime/proc.go:237 +0x35

goroutine 3 [GC sweep wait]:
runtime.gopark(0x412fe90, 0x41d1080, 0x4128b4e, 0xd, 0x401ee14, 0x1)
	/usr/local/Cellar/go/1.10/libexec/src/runtime/proc.go:291 +0x11a fp=0xc420044f60 sp=0xc420044f40 pc=0x402cd4a
runtime.goparkunlock(0x41d1080, 0x4128b4e, 0xd, 0x14, 0x1)
	/usr/local/Cellar/go/1.10/libexec/src/runtime/proc.go:297 +0x5e fp=0xc420044fa0 sp=0xc420044f60 pc=0x402cdfe
runtime.bgsweep(0xc420072000)
	/usr/local/Cellar/go/1.10/libexec/src/runtime/mgcsweep.go:52 +0xa3 fp=0xc420044fd8 sp=0xc420044fa0 pc=0x401ee63
runtime.goexit()
	/usr/local/Cellar/go/1.10/libexec/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc420044fe0 sp=0xc420044fd8 pc=0x40558b1
created by runtime.gcenable
	/usr/local/Cellar/go/1.10/libexec/src/runtime/mgc.go:216 +0x58

goroutine 18 [finalizer wait]:
runtime.gopark(0x412fe90, 0x41ed3b8, 0x4128df2, 0xe, 0x14, 0x1)
	/usr/local/Cellar/go/1.10/libexec/src/runtime/proc.go:291 +0x11a fp=0xc420040718 sp=0xc4200406f8 pc=0x402cd4a
runtime.goparkunlock(0x41ed3b8, 0x4128df2, 0xe, 0x14, 0x1)
	/usr/local/Cellar/go/1.10/libexec/src/runtime/proc.go:297 +0x5e fp=0xc420040758 sp=0xc420040718 pc=0x402cdfe
runtime.runfinq()
	/usr/local/Cellar/go/1.10/libexec/src/runtime/mfinal.go:175 +0xad fp=0xc4200407e0 sp=0xc420040758 pc=0x4015f0d
runtime.goexit()
	/usr/local/Cellar/go/1.10/libexec/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc4200407e8 sp=0xc4200407e0 pc=0x40558b1
created by runtime.createfing
	/usr/local/Cellar/go/1.10/libexec/src/runtime/mfinal.go:156 +0x62
exit status 2
```

**Comment by vladimirvivien** [comment]
@carlosmorales-glu I havent tested this on 1.10 nor on Mac.  So I don't know if it will work.  Thanks for pointing this out.

**Comment by vladimirvivien** [comment]
@carlosmorales-glu reading the output, it's possible that you may need to recompile all plugins to target Darwin.  I will give that a try to see if it works.

**Comment by vladimirvivien** [comment]
Closing. Plugin works on Darwin.
